[general]
import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.93
padding = { x = 15, y = 15 }
dynamic_padding = true
decorations = "None"
startup_mode = "Windowed"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 11
offset = { x = 0, y = 0 }

